-- Live Supabase schema (project tlfllnfwynaykxglsqhc) — already applied.
-- Kept here as the source of truth for local/docs alignment.
create table if not exists public.job_runs (
    id integer generated by default as identity primary key,
    job_name character varying not null,
    target_date date not null,
    status character varying not null
        check (status in ('pending', 'processing', 'completed', 'failed')),
    started_at timestamptz,
    finished_at timestamptz,
    error_message text,
    created_at timestamptz not null default now()
);

create index if not exists job_runs_target_date_idx on public.job_runs (target_date);
create index if not exists job_runs_status_idx on public.job_runs (status);
create index if not exists job_runs_created_at_idx on public.job_runs (created_at desc);

-- processing status IS the distributed lock: at most one processing row per job key
create unique index if not exists job_runs_one_processing_per_target
    on public.job_runs (job_name, target_date)
    where (status = 'processing');
